start: meta* type+
meta: NAME ":" JSON
type: stype | ftype

stype: NAME "=" ( "Binary" binary_opts COMMENT
    | "Boolean" boolean_opts COMMENT
    | "Integer" integer_opts COMMENT
    | "Number"  number_opts  COMMENT
    | "String"  string_opts  COMMENT
    | "ArrayOf" arr_of_opts  COMMENT
    | "MapOf"   map_of_opts  COMMENT )

ftype: NAME "=" ( "Array" array_opts COMMENT field*
    | "Map"     map_opts     COMMENT field*
    | "Record"  record_opts  COMMENT field*
    | "Enumerated" enum_opts COMMENT item*
    | "Choice"  choice_opts  COMMENT field* )

binary_opts:
boolean_opts:
integer_opts:
number_opts:
string_opts:
arr_of_opts:
map_of_opts:
array_opts:
map_opts:
record_opts:
enum_opts:
choice_opts:

item: INT STR COMMENT
field: INT FIELDNAME (TYPEREF|stype)

STR: /.+/
JSON: /.+[^\n]*/ NEWLINE

NAME: LETTER ("_"|"-"|LETTER|DIGIT)*
TYPENAME: LETTER ("_"|"-"|LETTER|DIGIT)*
FIELDNAME: LETTER ("_"|LETTER|DIGIT)*
TYPEREF: NSID? TYPENAME
NSID: LCASE_LETTER+ ":"

//
// Lark
//
LCASE_LETTER: "a".."z"
UCASE_LETTER: "A".."Z"
DIGIT: "0".."9"
LETTER: UCASE_LETTER | LCASE_LETTER
INT: DIGIT+
WORD: LETTER+

ESCAPED_IDENTIFIER: /\\([^\s]+)/
COMMENT: (" // " /[^\n]*/)? NEWLINE
MULTILINE_COMMENT: /\/\*(\*(?!\/)|[^*])*\*\//

WS_INLINE: (" "|/\t/)+
WS: /[ \t\f\r\n]/+

CR : /\r/
LF : /\n/
NEWLINE: (CR? LF)+

// %import common.ESCAPED_STRING
%ignore WS_INLINE
// %ignore COMMENT
// %ignore MULTILINE_COMMENT
// %ignore NEWLINE