start: meta* type+

meta: METADEF JSON

type: TYPEDEF ( "Binary"  binary_opts  COMMENT
    | "Boolean" boolean_opts COMMENT
    | "Integer" integer_opts COMMENT
    | "Number"  number_opts  COMMENT
    | "String"  string_opts  COMMENT
    | "ArrayOf" arr_of_opts  COMMENT
    | "MapOf"   map_of_opts  COMMENT
    | "Array"   array_opts   COMMENT array
    | "Map"     map_opts     COMMENT map
    | "Record"  record_opts  COMMENT record
    | "Enumerated" enum_opts COMMENT enumerated
    | "Choice"  choice_opts  COMMENT choice )

binary_opts:
boolean_opts:
integer_opts:
number_opts:
string_opts:
arr_of_opts:
map_of_opts:
array_opts:
map_opts:
record_opts:
enum_opts:
choice_opts:

array:
map:
record:
enumerated:
choice:

JSON: /.+[^\n]*/ NEWLINE

METADEF: LETTER ("_"|LETTER|DIGIT)* ":"
TYPEDEF: LETTER ("_"|LETTER|DIGIT)* /\s*=\s*/

LCASE_LETTER: "a".."z"
UCASE_LETTER: "A".."Z"
DIGIT: "0".."9"
LETTER: UCASE_LETTER | LCASE_LETTER
WORD: LETTER+

// 8. General

// Lark
ESCAPED_IDENTIFIER: /\\([^\s]+)/
COMMENT: "//" /[^\n]*/ NEWLINE
NEWLINE: "\n"
MULTILINE_COMMENT: /\/\*(\*(?!\/)|[^*])*\*\//


%import common.ESCAPED_STRING
%import common.WS

%ignore WS
%ignore COMMENT
%ignore MULTILINE_COMMENT
%ignore NEWLINE